#############################################################################
# Makefile for building: GraphLayout
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  GraphLayout.pro
# Template: subdirs
# Command: D:\Qt\Qt5.3.1\5.3\mingw482_32\bin\qmake.exe -spec win32-g++ -o Makefile GraphLayout.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.3.1\5.3\mingw482_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-GraphLayoutLibrary \
		sub-GraphLayoutLibraryClient


sub-GraphLayoutLibrary-qmake_all:  FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile
	cd GraphLayoutLibrary\ && $(MAKE) -f Makefile qmake_all
sub-GraphLayoutLibrary: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-GraphLayoutLibrary-make_first-ordered: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GraphLayoutLibrary-make_first: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GraphLayoutLibrary-all-ordered: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GraphLayoutLibrary-all: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GraphLayoutLibrary-clean-ordered: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GraphLayoutLibrary-clean: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GraphLayoutLibrary-distclean-ordered: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GraphLayoutLibrary-distclean: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GraphLayoutLibrary-install_subtargets-ordered: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GraphLayoutLibrary-install_subtargets: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GraphLayoutLibrary-uninstall_subtargets-ordered: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-GraphLayoutLibrary-uninstall_subtargets: FORCE
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-GraphLayoutLibraryClient-qmake_all: sub-GraphLayoutLibrary-qmake_all FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile
	cd GraphLayoutLibraryClient\ && $(MAKE) -f Makefile qmake_all
sub-GraphLayoutLibraryClient: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-GraphLayoutLibraryClient-make_first-ordered: sub-GraphLayoutLibrary-make_first-ordered  FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GraphLayoutLibraryClient-make_first: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GraphLayoutLibraryClient-all-ordered: sub-GraphLayoutLibrary-all-ordered  FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GraphLayoutLibraryClient-all: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GraphLayoutLibraryClient-clean-ordered: sub-GraphLayoutLibrary-clean-ordered  FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GraphLayoutLibraryClient-clean: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GraphLayoutLibraryClient-distclean-ordered: sub-GraphLayoutLibrary-distclean-ordered  FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GraphLayoutLibraryClient-distclean: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GraphLayoutLibraryClient-install_subtargets-ordered: sub-GraphLayoutLibrary-install_subtargets-ordered  FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GraphLayoutLibraryClient-install_subtargets: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GraphLayoutLibraryClient-uninstall_subtargets-ordered: sub-GraphLayoutLibrary-uninstall_subtargets-ordered  FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-GraphLayoutLibraryClient-uninstall_subtargets: FORCE
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: GraphLayout.pro D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/qdevice.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/device_config.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/common/shell-win32.conf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/qconfig.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/default_post.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/yacc.prf \
		D:/Qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/lex.prf \
		GraphLayout.pro
	$(QMAKE) -spec win32-g++ -o Makefile GraphLayout.pro
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\spec_pre.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\qdevice.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\device_config.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\common\shell-win32.conf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\qconfig.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_clucene_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_core.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_help.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_network.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_script.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\qt_functions.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\qt_config.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\qt_config.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\win32-g++\qmake.conf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\spec_post.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\exclusive_builds.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\default_pre.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\default_pre.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\resolve_config.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\default_post.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\rtti.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\precompile_header.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\warn_on.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\windows.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\testcase_targets.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\exceptions.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\yacc.prf:
D:\Qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\lex.prf:
GraphLayout.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile GraphLayout.pro

qmake_all: sub-GraphLayoutLibrary-qmake_all sub-GraphLayoutLibraryClient-qmake_all FORCE

make_first: sub-GraphLayoutLibrary-make_first-ordered sub-GraphLayoutLibraryClient-make_first-ordered FORCE
all: sub-GraphLayoutLibrary-all-ordered sub-GraphLayoutLibraryClient-all-ordered FORCE
clean: sub-GraphLayoutLibrary-clean-ordered sub-GraphLayoutLibraryClient-clean-ordered FORCE
distclean: sub-GraphLayoutLibrary-distclean-ordered sub-GraphLayoutLibraryClient-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-GraphLayoutLibrary-install_subtargets-ordered sub-GraphLayoutLibraryClient-install_subtargets-ordered FORCE
uninstall_subtargets: sub-GraphLayoutLibrary-uninstall_subtargets-ordered sub-GraphLayoutLibraryClient-uninstall_subtargets-ordered FORCE

sub-GraphLayoutLibrary-debug_ordered:
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
sub-GraphLayoutLibraryClient-debug_ordered: sub-GraphLayoutLibrary-debug_ordered 
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-GraphLayoutLibrary-debug_ordered sub-GraphLayoutLibraryClient-debug_ordered

sub-GraphLayoutLibrary-release_ordered:
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
sub-GraphLayoutLibraryClient-release_ordered: sub-GraphLayoutLibrary-release_ordered 
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
release: sub-GraphLayoutLibrary-release_ordered sub-GraphLayoutLibraryClient-release_ordered

sub-GraphLayoutLibrary-check_ordered:
	@if not exist GraphLayoutLibrary\ mkdir GraphLayoutLibrary\ & if not exist GraphLayoutLibrary\ exit 1
	cd GraphLayoutLibrary\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibrary\GraphLayoutLibrary.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
sub-GraphLayoutLibraryClient-check_ordered: sub-GraphLayoutLibrary-check_ordered 
	@if not exist GraphLayoutLibraryClient\ mkdir GraphLayoutLibraryClient\ & if not exist GraphLayoutLibraryClient\ exit 1
	cd GraphLayoutLibraryClient\ && ( if not exist Makefile $(QMAKE) E:\PROJECTS\LayoutLibrary\GraphLayoutLibraryClient\GraphLayoutLibraryClient.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
check: sub-GraphLayoutLibrary-check_ordered sub-GraphLayoutLibraryClient-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

